[package]
name = "komet"
version = "0.1.0"
entrypoint = "src/komet.typ"
authors = ["Mc-Zen <https://github.com/Mc-Zen>"]
license = "MIT"
description = "Faster."
compiler = "0.11.0"

repository = "https://github.com/lilaq-project/komet"
keywords = ["algorithm"]
categories = ["scripting", "utility"]