name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    name: Tests (Rust)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test --package komet
      
      
  build:
    name: Build WASM plugin
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2

    - name: Install WASM target
      run: rustup target add wasm32-unknown-unknown
      
    - name: Build WASM plugin
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Upload WASM artifact
      uses: actions/upload-artifact@v4
      with:
        name: komet.wasm
        path: ./target/wasm32-unknown-unknown/release/komet_plugin.wasm

        
  checks:
    name: Check clippy and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --all-targets
      - run: cargo fmt --check --all


  test-typst:
    name: Tests (Typst)
    needs: build
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download WASM artifact        
        uses: actions/download-artifact@v4
        with:
          name: komet.wasm
          path: ./src

      - name: Install tytanic (binary)
        uses: taiki-e/install-action@v2
        with:
          tool: tytanic@0.2.2

      - name: Run test suite
        run: tt run --no-fail-fast

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 5